### PR TITLE
Add pry function

### PR DESCRIPTION
**Pull request by locochris**
Example usage:

```
  equality matcher
     1:     it "handles newlines properly"
     2:       string_with_newline_char="new
     3: line"
     4:       multiline_string='new
     5: line'
 =>  6:       pry
     7:       assert equal "$multiline_string" "$string_with_newline_char"
     8:     end
     9:
    10:     it "compares strings containing single quotes"
    11:       assert equal "a' b" "a' b"
[2] shpec-pry> echo "$multiline_string"
new
line
[2] shpec-pry> assert equal "1" "2"
    handles newlines properly
    (Expected [1] to equal [2])
[2] shpec-pry> assert equal "$multiline_string" "$string_with_newline_char"
    handles newlines properly
```

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
@locochris, I don't get what `pry` is supposed to do

**Comment by rylnd** [comment]
This seems really cool. Is there anything shpec-specific about it, though? This seems like a separate (albeit really useful) utility that we could recommend along with shpec (similar to `entr`).

**Comment by AdrieanKhisbe** [comment]
My bad. after a second reread, now i see perfectly the goal.

(I thought that w&as a reference to ruby repl, but I should look for a translation: http://dictionnaire.reverso.net/anglais-francais/pry
haha)

**Comment by locochris** [comment]
@rylnd - `entr`? - but yer perhaps a separate utility?  I'm just finding it really useful when doing development driven testing (ie. lazily figuring out exactly how best to test what I've written by poking around in a subshell), so thought i'd chuck it up as a PR in case anyone also found it useful.

**Comment by rylnd** [comment]
@locochris `entr` was suggested in #45, and I promptly added it to the README. If you want to package this up, I'd love to do something similar. An alternative is to add some kind of "shpec recipes" section to the wiki, where we can share neat little tricks with `entr` or `shpec-pry` or whatever.

**Comment by rylnd** [comment]
If we could extract this to a `shpec-pry` function/executable, that one could install separately and then call from within a test (as above, but without modifying `shpec` itself), that seems like the ideal scenario.

@locochris, is that at all possible?

**Comment by hlangeveld** [comment]
On 05/07/15 20:35, Ryland Herrick wrote:
> If we could extract this to a |shpec-pry| function/executable, that one could install separately and then call from within a test
> (as above, but without modifying |shpec| itself), that seems like the ideal scenario.
>
> @locochris <https://github.com/locochris>, is that at all possible?


As |pry| has to be a bash function, it would be easy to deliver it as an extension to anyone using shpec with bash,
and we should not stop that.  However, it does depend strongly on the bash |caller| built-in, so it can't be loaded
run as an external command, nor would it work with any other of the shells we've tested so far.

Inconveniently, bash does not have a native function autoload feature, like ksh's FPATH, so shpec would need a way of
importing function definitions as extensions, just like we now add custom matcher functions.

Henk

**Comment by rylnd** [comment]
@locochris I'd like to make this a plugin (perhaps the first!); see #108 for details. I'm going to close this because it won't be merged to master. I've added a label here so that once #108 is ready we can take another pass at converting these to plugins.

**Pull request closed without merging**
