### PR TITLE
Features/improved dsl

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Follow up on #53.

Add `run` and  `async` commands. (plus code helper functions)

Some other changes might be considered before merging:
- check didn't break the `vim`shebang
- clean function
- assigns function 
- after/before (coule and maybe shoud be handled in other pr)
- others evocated on #53

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
note to self: lint recommandation to apply

**Comment by AdrieanKhisbe** [comment]
@rylnd should we do a dedicated branch on your repo so we can be several to collaborate, and do incremental PR. (branch we will merge back into trunk once we have settle what we want to add to the dsl.

**Comment by AdrieanKhisbe** [comment]
just rebase on top of latest PR merged

**Comment by rylnd** [comment]
@AdrieanKhisbe I like the idea behind `iok` and `iwarn` (although maybe green, yellow and red, `isuccess`, `iwarning`, and `ifailure`), but I'm not convinced of the value of the other functions:

* `clean` seems dangerous. It's just an alias to `rm` without telling (warning may be more appropriate) the user that it's an alias to `rm`. As a user, if a library provides me with such a function, I would expect it to do something in addition to the builtin. As it stands, its only purpose (to me) is to make me type more characters and potentially forget that it's really `rm`. If your intention was to expand its responsibility in the future, I would rather wait until that functionality is there.

* `load` is similar to `clean` in my mind; it's a thin wrapper around `.` that (again, in my opinion) only serves to obfuscate what's actually happening. The same "if this was meant to do more, let's merge it when it does more" caveat applies here.

* `run` and `async` have similar notes to those above.

In general, my reaction to these functions is that until the advantages provided by the function outweigh the obfuscation caused by using them, we shouldn't force users to use them (nor clutter the codebase with them). What I would _prefer_ (for now) is that the tests that inspired/necessitated those helpers be documented in [our examples section](https://github.com/rylnd/shpec/wiki/Examples). This would provide both a list of common patterns for users to build on, and it would also help us document common use cases and determine things like:

* what tasks work well
* what tasks takes a lot of code to accomplish
* what tasks are wholly illegible

**Comment by AdrieanKhisbe** [comment]
I understand your concern.

The point about the `run`, `async`, `clean`, `load` is that we don't run command directly.
Which will ease the pending test implementation.
This would also enable to add feature on the go of the function, printing the command for instance.

**Comment by AdrieanKhisbe** [comment]
@rylnd 
Do you want me to try to implement the `xit`/`xdescribe` feature, along with the debug, verbose mode.
(the two big features that would be enable by the commands)

**Comment by AdrieanKhisbe** [comment]
(oups, bad manipulaation for the request review)

**Comment by AdrieanKhisbe** [comment]
Closing with lack of interest

**Pull request closed without merging**
