### PR TITLE
Fix zsh plugin and arguments with whitespaces

### PR DESCRIPTION
**Pull request by ezh**
Broken https://travis-ci.org/ezh/shpec/builds/217703619
Fixed https://travis-ci.org/ezh/shpec/jobs/217730218

Addresses #102

### CODE REVIEW

**Comment by rylnd** [comment]
@ezh I'm having a lot understanding what's going on here, and I'm going to need clarification before I consider merging this. A few notes:

1. If the multiple-argument issues are separate from #102, please address those in a separate PR; having that work here makes both solutions harder to understand.
2. The more zsh-specific logic that we can put in the plugin itself, the better. shpec is meant to be POSIX-compliant, and we should not be bending over backwards special-casing non-standard shells' behavior.
3. The .travis.yml was bad before, but it's getting out of control; we need to figure out how better to organize our build.
4. Given the choice between:
    a. Explaining the code in the commit message
    b. Explaining the code in a comment
    c. Not explaining the code
I am always going to prefer a.

**Comment by ezh** [comment]
You may do as you wish.
Since I have near broken shpec under zsh, I just fix it.
I showed errors in https://travis-ci.org/ezh/shpec/builds/217703619
**Could you please merge it to separate branch and relayout them as you think is correct? Since the commits is very little**
I prefer not to use telepathy.

I have concern about your point:
If I make PR with better travis.yml, then CI build will be broken. Will you merge broken code to master?
Would 1. is separate from issue? I don't think so - #102 that arguments in zsh is broken. As side effect we know right now that it is broken everywhere.

I suspect that copy'n'paste of working solution between files is relatively easy job.

The only blocker is 2: move zsh specific code to plugin (minute or two of work - cut text from bin/shpec, add explicit find to zsh plugin).

1. What do you think? Did you merge it to separate branch and re layout for you pleasure?
2. I could move zsh specific code to plugin. Is this enough?
3. Or please provide me instruction what is my next step to fix it up.

With hope that shpec will be fixed 😄

**Comment by ezh** [comment]
I see here two different problems:
formal: PR not POSIX compilant - I could fix it
informal: I don't like this/that, this/that is not verbose(for whom?), it is not so right... - I could't fix it

* API not changed
* modification are test covered
* new functions are absent - nothing changed

So except the POSIX part formal patch is correct.
I hope I explain my thought 🤔

**Comment by rylnd** [comment]
@ezh I understand your concerns; I too want the zsh plugin to be fixed.

I think that I misunderstood this branch's description; let me try to summarize the issues:

1. The zsh plugin does not allow arguments to be passed (#102)
2. shpec does not handle arguments with whitespace (issue not yet opened)
3. We have no unit tests around calling function itself (w/ or w/o arguments), and thus have no way of testing either of the aforementioned issues.

@ezh assuming my understanding is correct, I would still prefer to address issues 1) and 2) separately. As you have requested, I will create a branch that provides some regression tests for 1) and possibly 2) as well. With that in place, we can come to a good solution together! I will have that done sometime this week.

Thank you again for your insight into this issue and the time taken to address it. I appreciate that you've found a solution, but I hope that you can also appreciate my discrimination; if I understand neither the "how" nor the "why" of some code, I have no hope of maintaining it, which is the quickest way to kill an OSS project.

**Comment by ezh** [comment]
All points 1-3 are correct.
It is a great pleasure that we have a conversation.
My only interest is working solution - all other are insignificantly (my PR too)

P.S. About live or dead OSS projects - I already involved in OSS [salt](https://github.com/saltstack/salt) with 25k PRs. Their community live within KPI, formal rules and extreme evolution rate. There are no I like/I don't like, more verbose/less verbose. I'm sure that there are more that one way to target. You may follow your own.

**Comment by rylnd** [comment]
@ezh I've added a branch with some failing tests; see the details in #112. If you have the time, I would greatly appreciate a PR to address that issue be based on said branch.

I am still working on doing the same for the #102; I will let you know as soon as that's done.

Thanks!

**Pull request closed without merging**
