### PR TITLE
provide shebang: `/bin/sh` for fish compatibility, closes #118

### LINKED ISSUE #118: fish support
trying to run with fish fails with:

	fish_1     | Failed to execute process '/usr/local/bin/shpec'. Reason:
	fish_1     | exec: unknown error (errno was 8)
	fish_1     | The file '/usr/local/bin/shpec' is marked as an executable but could not be run by the operating system.

### PR DESCRIPTION
**Pull request by typekpb**

### CODE REVIEW

**Comment by typekpb** [comment]
obviously things are not as easy as I originally expected, any chance for help on failing fish travis-ci job?

**Comment by rylnd** [comment]
@typekpb thanks for investigating this. It seems that fish is [pretty straightforward](https://github.com/fish-shell/fish-shell/wiki/POSIX-compatibility-thoughts) about their support of the POSIX standard (or lack thereof).

Personal opinions aside, this looks to be a non-trivial amount of work to convert shpec to use fish-supported constructs; there's also the possibility that we do some things in shpec that would need to be rewritten entirely.

Given that this is the first request for fish compatibility, I'm inclined to believe that there is not a strong need for it, but I am always happy to be corrected by the community at large on that assertion. I'm _more_ than happy to accept a PR that provides fish compatibility, of course.

@typekpb it does look like fish gives you useful feedback in regards to what it doesn't like; between that and the test suite(s) you should have some decent guard rails for getting this working if you so choose. I'm more than happy to answer more pointed questions if you do get stuck on a particular problem, too. Feel free to ask on this PR, or on gittr, or wherever you can find me ;)

**Comment by rylnd** [comment]
@typekpb are there any updates here? Does this PR work for you locally, or do the test failures provide an accurate picture of using shpec with fish?

**Comment by typekpb** [comment]
@rylnd no progress on my side. never worked for me locally. I was originally expecting this one to be a low hanging fruit, which obviously is not :) closing

**Pull request closed without merging**
