### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### rylnd/shpec now has a Chat Room on Gitter

@AdrieanKhisbe has just created a chat room. You can visit it here: [https://gitter.im/rylnd/shpec](https://gitter.im/rylnd/shpec?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/rylnd/shpec?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by rylnd** [comment]
@AdrieanKhisbe I'm fine with having a Gitter room if there's ever a case where we would need quick communication. However, I don't want to add another data source for actionable shpec items.

If there are questions to answer or issues to address, I want them to be on GitHub; requiring me (and everyone else) to check GitHub _and_ Gitter seems painful.

Let me know if you feel differently or envision a different use case for Gitter.

**Comment by AdrieanKhisbe** [comment]
That was for the quick communication. In fact just end up on gitter this morning, and didn't know would trigger a pull request. Sorry for that @rylnd.I totally agree that every discussion are better on Github through issue!

**Comment by AdrieanKhisbe** [comment]
so for that better to close it ;). 
I let you the pleasure unless you insist

**Comment by rylnd** [comment]
Heh, no worries, I did the same thing in #51.

**Comment by AdrieanKhisbe** [comment]
kill all the false fork!!!! ^^

**Comment by AdrieanKhisbe** [comment]
(I'll be around on gittr whenever you wanna discuss interactively about the language extension I started proposing)

**Pull request closed without merging**
