### PR TITLE
add minimal emacs derived mode

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
as commit name says

### CODE REVIEW

**Comment by rylnd** [comment]
I have every intention to add this, and as mentioned in #49 I'd love to add a syntax file for vim as well.

I'd like to see how other projects are packaging these sorts of files. Special folder, branch, or a separate repo entirely?

**Comment by AdrieanKhisbe** [comment]
Don't know for sure. for some might be separate repo. (rspec-mode), but would feel a bit presompuous. 
However, this should be indeed publish on vundle and melpa once mature enough

We should dig for how similar project do. (first define what similar is ^^

**Comment by AdrieanKhisbe** [comment]
@rylnd, did you have opportunity to see how similar project do?

@hlangeveld @locochris, any suggestion ? :)

**Comment by rylnd** [comment]
Maybe this should just be a separate repo?

**Comment by AdrieanKhisbe** [comment]
mmmm. why not. 
But would be good then to move them to [shpec organisation(https://github.com/shpec).

**Comment by AdrieanKhisbe** [comment]
I just see :). Shall we rename it `shpec-mode` (would be clear it's an emacs mode).
(I don't have right to do this).

Should we move shpec to shpec then? ^^

**Comment by rylnd** [comment]
Renamed.

**Comment by AdrieanKhisbe** [comment]
Perfect, will do this tomorrow along with a readme and else.

Closing

**Comment by AdrieanKhisbe** [comment]
I didn't realize your renamed it `emacs-mode`, `shpec-mode` will be more clear, specially if we make an `el-get` recipe or publish it to `melpa`. (at least `shpec-mode.el` if you really want to make more than explicit it's emacs related.

*sorrry* :/

**Pull request closed without merging**
