### PR TITLE
fix: allow spaces in matches

### PR DESCRIPTION
**Pull request by binaryphile**

### CODE REVIEW

**Comment by binaryphile** [comment]
Addresses #103

**Comment by rylnd** [comment]
@binaryphile I'm all about this if you can get the test suite green.

**Comment by rylnd** [comment]
@binaryphile this might be obviated by #97, but at the very least we can still use your tests to better document the behavior of whichever matchers we decide should come out of that PR.

**Comment by binaryphile** [comment]
I've found a way to do this without matchers.  I'll close my pull request.

**Pull request closed without merging**
